class SettingsMap():
    enemys = int()
    respawnEnemys = int()
    playerPosition = ()
    bonuses = int()
    wallsSpawns = int()
    vizibleZone = int()
    removeHealth = int()
    maxMembers = int()
    difficult = int()
    bonusUp = float()